import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, Bell, CalendarDays, ChevronRight, Clock3, FlaskConical, LayoutDashboard, Menu, Package, Pill, Plus, Search, Settings, ShoppingCart, Stethoscope, UserRound, Users, X } from 'lucide-react';
import './styles.css';

type Patient = { id:string; name:string; age:number; phone:string; gender:string; address:string; lastVisit:string; status:string };
type QueueItem = { id:string; patientId:string; patientName:string; doctor:string; type:string; token:number; status:string; time:string };
type Medicine = { name:string; batch:string; expiry:string; stock:number; mrp:number };

const initialPatients: Patient[] = [
 {id:'P-10021',name:'Ravi Kumar',age:48,phone:'98•••••210',gender:'Male',address:'Warangal',lastVisit:'12 Sep 2026',status:'OPD'},
 {id:'P-10020',name:'S. Lakshmi',age:35,phone:'97•••••641',gender:'Female',address:'Hanamkonda',lastVisit:'12 Sep 2026',status:'Lab'},
 {id:'P-10019',name:'Mohammed Imran',age:61,phone:'99•••••812',gender:'Male',address:'Kazipet',lastVisit:'11 Sep 2026',status:'IPD'},
 {id:'P-10018',name:'Anitha Reddy',age:29,phone:'96•••••308',gender:'Female',address:'Warangal',lastVisit:'11 Sep 2026',status:'Completed'}
];
const initialQueue: QueueItem[] = [
 {id:'Q1',patientId:'P-10021',patientName:'Ravi Kumar',doctor:'Dr. Ramesh',type:'General OPD',token:21,status:'Waiting',time:'12:05 PM'},
 {id:'Q2',patientId:'P-10020',patientName:'S. Lakshmi',doctor:'Dr. Ramesh',type:'General OPD',token:22,status:'Waiting',time:'12:12 PM'},
 {id:'Q3',patientId:'P-10018',patientName:'Anitha Reddy',doctor:'Dr. Ramesh',type:'Follow-up',token:23,status:'In Consultation',time:'12:18 PM'}
];
const medicines: Medicine[] = [
 {name:'CORDAPA-10 TABLET',batch:'LGP10/116/07',expiry:'09/2027',stock:110,mrp:149.06},
 {name:'ALLEGRO-M',batch:'T6A5383',expiry:'04/2028',stock:62,mrp:119},
 {name:'GLIMICOR-M4 FORTE',batch:'BD252710',expiry:'10/2027',stock:18,mrp:186.56},
 {name:'MYLINCOR-PLUS',batch:'BH62106',expiry:'04/2027',stock:8,mrp:258}
];
const nav = [['Dashboard',LayoutDashboard],['Patients',Users],['OPD',Stethoscope],['IPD & Beds',Activity],['Laboratory',FlaskConical],['Pharmacy',Pill],['Billing',ShoppingCart],['WhatsApp & AI PRO',Bell]] as const;

function App(){
 const [active,setActive]=useState('Dashboard'); const [menuOpen,setMenuOpen]=useState(false); const [showPatient,setShowPatient]=useState(false); const [showScan,setShowScan]=useState(false); const [query,setQuery]=useState('');
 const [patients,setPatients]=useState(initialPatients); const [queue,setQueue]=useState(initialQueue);
 const filtered=useMemo(()=>patients.filter(p=>`${p.name} ${p.id} ${p.phone}`.toLowerCase().includes(query.toLowerCase())),[patients,query]);
 const register=(data:{name:string;age:number;gender:string;phone:string;address:string})=>{const id=`P-${10022+patients.length-4}`; const p:Patient={...data,id,lastVisit:'12 Sep 2026',status:'OPD'}; setPatients(v=>[p,...v]); setActive('Patients'); setShowPatient(false);};
 const addToQueue=(patient:Patient,doctor:string,type:string)=>{const token=queue.length?Math.max(...queue.map(q=>q.token))+1:1;setQueue(v=>[...v,{id:`Q${Date.now()}`,patientId:patient.id,patientName:patient.name,doctor,type,token,status:'Waiting',time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}]);};
 return <div className="app">
  <aside className={menuOpen?'sidebar open':'sidebar'}><div className="brand"><div className="brandMark">AI</div><div><strong>AI PRO</strong><span>Hospital OS</span></div><button className="mobileClose" onClick={()=>setMenuOpen(false)}><X size={20}/></button></div>
   <div className="hospital"><div className="hospitalIcon">🏥</div><div><strong>Lakshmi Narasimha</strong><span>Hospital</span></div></div>
   <nav>{nav.map(([label,Icon])=><button key={label} className={active===label?'navItem active':'navItem'} onClick={()=>{setActive(label);setMenuOpen(false)}}><Icon size={19}/><span>{label}</span>{label==='WhatsApp & AI PRO'&&<i>AI</i>}</button>)}</nav>
   <div className="sidebarBottom"><button className="navItem"><Settings size={19}/><span>Settings</span></button><div className="user"><div className="avatar">DR</div><div><strong>Hospital Admin</strong><span>Administrator</span></div></div></div>
  </aside>
  <main className="main"><header className="topbar"><button className="hamburger" onClick={()=>setMenuOpen(true)}><Menu/></button><div className="pageTitle"><span>Good afternoon</span><h1>{active}</h1></div><div className="topActions"><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search patient, medicine..."/></div><button className="iconBtn"><Bell size={19}/><b></b></button><div className="topAvatar">DR</div></div></header>
   {active==='Dashboard'&&<Dashboard patients={patients} queue={queue} onNew={()=>setShowPatient(true)} onScan={()=>setShowScan(true)} onOPD={()=>setActive('OPD')}/>} 
   {active==='Patients'&&<Patients patients={filtered} onNew={()=>setShowPatient(true)} onQueue={p=>{addToQueue(p,'Dr. Ramesh','General OPD');setActive('OPD')}}/>}
   {active==='OPD'&&<OPD queue={queue} patients={patients} onNew={()=>setShowPatient(true)} onQueue={addToQueue}/>} 
   {active==='Pharmacy'&&<Pharmacy onScan={()=>setShowScan(true)}/>} 
   {active!=='Dashboard'&&active!=='Patients'&&active!=='OPD'&&active!=='Pharmacy'&&<Placeholder title={active}/>} 
  </main>
  {showPatient&&<Modal title="Register New Patient" close={()=>setShowPatient(false)}><PatientForm onSave={register} close={()=>setShowPatient(false)}/></Modal>}
  {showScan&&<Modal title="AI Invoice → Stock" close={()=>setShowScan(false)}><InvoiceScan close={()=>setShowScan(false)}/></Modal>}
 </div>;
}

function Dashboard({patients,queue,onNew,onScan,onOPD}:{patients:Patient[];queue:QueueItem[];onNew:()=>void;onScan:()=>void;onOPD:()=>void}){return <section className="content"><div className="welcome"><div><h2>Hospital overview</h2><p>Live staff workflow for today.</p></div><div className="date"><CalendarDays size={17}/>12 September 2026</div></div><div className="stats"><Stat icon={<Users/>} label="Patients today" value={String(patients.length)} delta="Live"/><Stat icon={<Stethoscope/>} label="OPD waiting" value={String(queue.filter(q=>q.status==='Waiting').length)} delta="Queue"/><Stat icon={<FlaskConical/>} label="Lab tests" value="27" delta="+15%"/><Stat icon={<ShoppingCart/>} label="Today’s collection" value="₹86,420" delta="+11%"/></div><div className="quick"><div className="sectionHead"><div><h3>Quick actions</h3><p>Common tasks for your staff</p></div></div><div className="quickGrid"><Action icon={<UserRound/>} title="New patient" text="Register patient" onClick={onNew}/><Action icon={<CalendarDays/>} title="OPD queue" text="Book / manage token" onClick={onOPD}/><Action icon={<Pill/>} title="Pharmacy" text="Open inventory"/><Action icon={<Package/>} title="Scan purchase bill" text="AI stock entry" onClick={onScan}/></div></div><div className="grid2"><div className="panel"><div className="sectionHead"><div><h3>Today’s OPD queue</h3><p>Latest patient visits</p></div><button className="linkBtn" onClick={onOPD}>View queue <ChevronRight size={16}/></button></div><QueueTable queue={queue}/></div><div className="panel"><div className="sectionHead"><div><h3>Pharmacy alerts</h3><p>Needs staff attention</p></div></div><Alert title="8 medicines" text="Low stock" type="warning"/><Alert title="14 batches" text="Expiring within 90 days" type="danger"/><Alert title="1 invoice" text="Waiting for stock confirmation" type="info"/></div></div></section>}

function Patients({patients,onNew,onQueue}:{patients:Patient[];onNew:()=>void;onQueue:(p:Patient)=>void}){return <section className="content"><div className="pageActions"><div><h2>Patient registry</h2><p>Search, register and send a patient directly to OPD.</p></div><button className="primary" onClick={onNew}><Plus size={18}/> New patient</button></div><div className="panel"><div className="tableWrap"><table><thead><tr><th>Patient</th><th>ID</th><th>Age</th><th>Phone</th><th>Last visit</th><th>Status</th><th>Action</th></tr></thead><tbody>{patients.map(p=><tr key={p.id}><td><strong>{p.name}</strong></td><td>{p.id}</td><td>{p.age}</td><td>{p.phone}</td><td>{p.lastVisit}</td><td><span className={`badge ${p.status.toLowerCase()}`}>{p.status}</span></td><td><button className="secondary" onClick={()=>onQueue(p)}>Add to OPD</button></td></tr>)}</tbody></table></div></div></section>}

function OPD({queue,patients,onNew,onQueue}:{queue:QueueItem[];patients:Patient[];onNew:()=>void;onQueue:(p:Patient,d:string,t:string)=>void}){const [patientId,setPatientId]=useState(patients[0]?.id||'');const [doctor,setDoctor]=useState('Dr. Ramesh');const [type,setType]=useState('General OPD');const selected=patients.find(p=>p.id===patientId);return <section className="content"><div className="pageActions"><div><h2>OPD & Token Queue</h2><p>Register a visit, generate token and manage consultation flow.</p></div><button className="primary" onClick={onNew}><Plus size={18}/> New patient</button></div><div className="grid2"><div className="panel"><div className="sectionHead"><div><h3>New OPD visit</h3><p>Reception can complete this in a few clicks.</p></div></div><div className="form"><label>Patient<select value={patientId} onChange={e=>setPatientId(e.target.value)}>{patients.map(p=><option key={p.id} value={p.id}>{p.name} — {p.id}</option>)}</select></label><label>Doctor<select value={doctor} onChange={e=>setDoctor(e.target.value)}><option>Dr. Ramesh</option><option>Duty Doctor</option><option>Specialist</option></select></label><label>Visit type<select value={type} onChange={e=>setType(e.target.value)}><option>General OPD</option><option>Follow-up</option><option>Emergency</option></select></label><div className="patientMini"><strong>{selected?.name||'Select patient'}</strong><span>{selected?`${selected.age} yrs · ${selected.gender} · ${selected.phone}`:'Patient details'}</span></div><div className="modalActions"><button className="primary" disabled={!selected} onClick={()=>selected&&onQueue(selected,doctor,type)}><Plus size={16}/> Generate token</button></div></div></div><div className="panel"><div className="sectionHead"><div><h3>Live queue</h3><p>{queue.filter(q=>q.status==='Waiting').length} waiting</p></div><span className="badge opd"><Clock3 size={12}/> Today</span></div><QueueTable queue={queue}/></div></div></section>}

function QueueTable({queue}:{queue:QueueItem[]}){return <div className="tableWrap"><table><thead><tr><th>Token</th><th>Patient</th><th>Doctor</th><th>Visit</th><th>Time</th><th>Status</th></tr></thead><tbody>{queue.map(q=><tr key={q.id}><td><strong>#{q.token}</strong></td><td>{q.patientName}<small className="cellSub">{q.patientId}</small></td><td>{q.doctor}</td><td>{q.type}</td><td>{q.time}</td><td><span className={`badge ${q.status==='Waiting'?'warning':'completed'}`}>{q.status}</span></td></tr>)}</tbody></table></div>}
function Stat({icon,label,value,delta}:{icon:React.ReactNode;label:string;value:string;delta:string}){return <div className="stat"><div className="statIcon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{delta} <em>today</em></small></div></div>}
function Action({icon,title,text,onClick}:{icon:React.ReactNode;title:string;text:string;onClick?:()=>void}){return <button className="action" onClick={onClick}><div>{icon}</div><span><strong>{title}</strong><small>{text}</small></span><ChevronRight size={17}/></button>}
function Alert({title,text,type}:{title:string;text:string;type:string}){return <div className="alert"><div className={`alertDot ${type}`}></div><div><strong>{title}</strong><span>{text}</span></div><ChevronRight size={16}/></div>}
function Pharmacy({onScan}:{onScan:()=>void}){return <section className="content"><div className="pageActions"><div><h2>Pharmacy & Inventory</h2><p>Batch-wise stock, purchases and expiry management.</p></div><button className="primary" onClick={onScan}><Package size={18}/> Scan supplier bill</button></div><div className="stats"><Stat icon={<Package/>} label="Total items" value="1,284" delta="32 added"/><Stat icon={<Pill/>} label="Low stock" value="8" delta="Needs action"/><Stat icon={<CalendarDays/>} label="Expiring soon" value="14" delta="90 days"/><Stat icon={<ShoppingCart/>} label="Today purchases" value="₹52,480" delta="6 invoices"/></div><div className="panel"><div className="sectionHead"><div><h3>Current stock</h3><p>Batch and expiry tracking</p></div></div><div className="tableWrap"><table><thead><tr><th>Medicine</th><th>Batch</th><th>Expiry</th><th>Stock</th><th>MRP</th><th>Status</th></tr></thead><tbody>{medicines.map(m=><tr key={m.batch}><td><strong>{m.name}</strong></td><td>{m.batch}</td><td>{m.expiry}</td><td>{m.stock}</td><td>₹{m.mrp.toFixed(2)}</td><td><span className={`badge ${m.stock<20?'warning':'completed'}`}>{m.stock<20?'Low stock':'In stock'}</span></td></tr>)}</tbody></table></div></div></section>}
function Placeholder({title}:{title:string}){return <section className="content"><div className="empty"><div className="emptyIcon"><Activity/></div><h2>{title}</h2><p>This module is scaffolded and ready for its workflow implementation.</p><button className="primary">Configure module</button></div></section>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="overlay"><div className="modal"><div className="modalHead"><h2>{title}</h2><button onClick={close}><X/></button></div>{children}</div></div>}
function PatientForm({onSave,close}:{onSave:(d:{name:string;age:number;gender:string;phone:string;address:string})=>void;close:()=>void}){const [name,setName]=useState('');const [age,setAge]=useState('');const [gender,setGender]=useState('');const [phone,setPhone]=useState('');const [address,setAddress]=useState('');const valid=name.trim()&&age&&gender&&phone.length>=10;return <div className="form"><label>Full name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Patient name"/></label><div className="formRow"><label>Age<input value={age} onChange={e=>setAge(e.target.value)} type="number" placeholder="Age"/></label><label>Gender<select value={gender} onChange={e=>setGender(e.target.value)}><option value="">Select</option><option>Male</option><option>Female</option><option>Other</option></select></label></div><label>Mobile number<input value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,''))} maxLength={10} placeholder="10-digit mobile"/></label><label>Address<textarea value={address} onChange={e=>setAddress(e.target.value)} placeholder="Address"/></label><div className="modalActions"><button className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={!valid} onClick={()=>valid&&onSave({name:name.trim(),age:Number(age),gender,phone,address})}>Register patient</button></div></div>}
function InvoiceScan({close}:{close:()=>void}){const [confirmed,setConfirmed]=useState(false);return <div className="scan"><div className="dropzone"><Package size={34}/><strong>Supplier invoice detected</strong><span>AI PRO extracts medicine, batch, expiry, quantity, rate and GST, then asks staff to verify.</span><button className="secondary">Choose invoice</button></div><div className="invoiceSummary"><div><span>Supplier</span><strong>Lennox Lifesciences</strong></div><div><span>Invoice</span><strong>SS00458</strong></div><div><span>Date</span><strong>11/08/2026</strong></div><div><span>Items detected</span><strong>10</strong></div></div><div className="confidence">✓ AI extraction complete <span>98% confidence</span></div><div className="modalActions"><button className="secondary" onClick={close}>Cancel</button><button className="primary" onClick={()=>setConfirmed(true)}>{confirmed?'Stock added ✓':'Verify & add stock'}</button></div>{confirmed&&<p className="success">10 items queued for batch-wise stock update. Audit record created.</p>}</div>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
